In [5]:
import pandas as pd
import numpy as np

In [4]:
football_data=pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')

In [6]:
football_data

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

## rename columns

In [5]:
football_data=football_data.rename(columns={'Date':'Match Date', 'AwayTeam': 'Other team' })

In [6]:
football_data

,Div,Match Date,Time,HomeTeam,Other team,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [8]:
football_data=football_data.rename(columns={'FTAG':'other_team_goal','FTHG': 'home_team_goal'})

## Read .csv from Multiple URLs with Pandas

In [ ]:
# link structure
## Link: root + season + league
"https://www.football-data.co.uk/mmz4281/" + "2122" + "/" + "E0" + ".csv"

In [7]:
root='https://www.football-data.co.uk/mmz4281/'

## Loop

In [13]:
links = ['E0', 'E2', 'E3', 'E1', 'EC']
allLinks = []
for link in links:
    url = root + "2122/" + link + ".csv"
    print("Trying:", url)
    eachLink = pd.read_csv(url, encoding="unicode_escape")
    allLinks.append(eachLink)

Trying: https://www.football-data.co.uk/mmz4281/2122/E0.csv
Trying: https://www.football-data.co.uk/mmz4281/2122/E2.csv
Trying: https://www.football-data.co.uk/mmz4281/2122/E3.csv
Trying: https://www.football-data.co.uk/mmz4281/2122/E1.csv
Trying: https://www.football-data.co.uk/mmz4281/2122/EC.csv

In [14]:
len(allLinks)

5

In [22]:
allLinks[2].head(5)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,07/08/2021,15:00,Carlisle,Colchester,0,0,D,0,0,...,1.57,-0.25,1.75,2.05,1.78,2.13,1.82,2.13,1.75,2.08
1,E3,07/08/2021,15:00,Exeter,Bradford,0,0,D,0,0,...,1.65,0.00,1.80,2.05,1.79,2.12,1.87,2.12,1.80,2.03
2,E3,07/08/2021,15:00,Forest Green,Sutton,2,1,H,1,0,...,1.60,-0.25,1.98,1.83,1.93,1.95,2.03,1.99,1.91,1.90
3,E3,07/08/2021,15:00,Harrogate,Rochdale,3,2,H,2,1,...,1.78,-0.25,1.90,1.95,1.90,1.98,1.94,1.98,1.88,1.94
4,E3,07/08/2021,15:00,Hartlepool,Crawley Town,1,0,H,0,0,...,1.68,-0.25,1.90,1.95,1.93,1.95,1.96,1.98,1.90,1.91

In [23]:
allLinks[0].head(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12

## Get multiple season csv file at a time

In [3]:
for season in range(15,21):
    print(str(season) + str(season+1))

1516
1617
1718
1819
1920
2021

In [ ]:
links = ['E0', 'E2', 'E3', 'E1', 'EC']
all_csv_data = []

for link in links:
    for season in range(15, 21):  # range of seasons
        url = root + str(season) + str(season+1) + "/" + link + ".csv"
        each_csv = pd.read_csv(url, encoding="unicode_escape")

        each_csv.insert(1, 'season', season)  # make season a new column
        all_csv_data.append(each_csv)

In [20]:
len(all_csv_data)

23